FACE_LANDMARKER_MODEL_PATH = "models/face_landmarker.task"

ANTI_SPOOF_MODEL_PATH = "models/best_model.onnx"

ANTI_SPOOF_REAL_THRESHOLD = 0.60
ANTI_SPOOF_FAKE_THRESHOLD = 0.70

EAR_THRESHOLD = 0.22

HEAD_TURN_THRESHOLD = 35
HEAD_TURN_RATIO_THRESHOLD = 0.10

RANDOM_CHALLENGE_COUNT = 3
CHALLENGE_WARNING_SECONDS = 5
CHALLENGE_TIMEOUT_SECONDS = 10

SEVERE_BRIGHTNESS_MIN = 25
SEVERE_BRIGHTNESS_MAX = 245
SEVERE_BLUR_MIN = 10